name: Build and deploy Angular front-end and Django back-end to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Angular front-end build job
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Angular app
        run: |
          cd angular-17-crud-example-master
          npm install
          npm run build --prod

      - name: Zip Angular build artifact
        run: |
          cd angular-17-crud-example-master
          zip -r dist/angular-app.zip dist/

      - name: Upload Angular artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: angular-17-crud-example-master/dist/angular-app.zip

  # Django back-end build job
  build-django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Django
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r post-back-do-front-backend-master/requirements.txt

      - name: Run Django migrations
        run: |
          source venv/bin/activate
          cd post-back-do-front-backend-master
          python manage.py makemigrations
          python manage.py migrate

      - name: Zip Django back-end artifact
        run: |
          cd post-back-do-front-backend-master
          zip -r release-django.zip .

      - name: Upload Django artifact
        uses: actions/upload-artifact@v3
        with:
          name: django-backend
          path: post-back-do-front-backend-master/release-django.zip

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-angular
      - build-django
    steps:
      - name: Download Angular artifact
        uses: actions/download-artifact@v3
        with:
          name: angular-app

      - name: Download Django artifact
        uses: actions/download-artifact@v3
        with:
          name: django-backend

      - name: Deploy Angular front-end to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'angular-app-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ANGULAR }}
          package: angular-17-crud-example-master/dist/angular-app.zip

      - name: Deploy Django back-end to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'django-app-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DJANGO }}
          package: post-back-do-front-backend-master/release-django.zip
