name: Build and deploy Angular and Django app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js for Angular frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Build Angular frontend
      - name: Install and build Angular frontend
        working-directory: angular-17-crud-example-master
        run: |
          npm install
          npm run build --prod
          mv dist/angular-17-crud-example-master ../dist

      # Step 4: Set up Python environment for Django backend
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: post-back-do-front-backend-master
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 5: Apply Django migrations
      - name: Run Django migrations
        working-directory: post-back-do-front-backend-master
        run: |
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      # Step 6: Combine Angular and Django into deployment package
      - name: Prepare deployment package
        run: |
          cp -r angular-dist/* post-back-do-front-backend-master/static/
          zip -r release.zip post-back-do-front-backend-master

      # Step 7: Upload deployment artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Download deployment artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fullstack-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tejatyuu78888trrr'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: post-back-do-front-backend-master
