# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Angular and Django to Azure Web App - tejatyuu78888trrr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Frontend: Angular build
      - name: Set up Node.js for Angular
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Angular dependencies
        working-directory: ./angular-17-crud-example-master
        run: |
          npm install

      - name: Build Angular project
        working-directory: ./angular-17-crud-example-master
        run: |
          npm run build --if-present

      # Backend: Django setup and build
      - name: Set up Python for Django
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Django dependencies
        working-directory: ./post-back-do-front-backend-master
        run: |
          python -m pip install --upgrade pip
          pip install -r ./post-back-do-front-backend-master/requirements.txt

      - name: Set up Django environment and apply migrations
        working-directory: ./post-back-do-front-backend-master
        run: |
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      # Zip both frontend and backend artifacts for deployment
      - name: Zip Angular artifact for deployment
        working-directory: ./angular-17-crud-example-master
        run: |
          zip -r angular-release.zip dist/

      - name: Zip Django artifact for deployment
        working-directory: ./post-back-do-front-backend-master
        run: |
          zip -r django-release.zip .

      - name: Upload Angular artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: ./angular-17-crud-example-master/angular-release.zip

      - name: Upload Django artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: django-app
          path: ./post-back-do-front-backend-master/django-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Angular artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: angular-app

      - name: Download Django artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: django-app

      - name: Unzip Angular artifact for deployment
        run: unzip angular-release.zip -d ./angular-app

      - name: Unzip Django artifact for deployment
        run: unzip django-release.zip -d ./django-app

      - name: Deploy Angular to Azure Web App (Frontend)
        id: deploy-angular
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'angular-app-name'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_ANGULAR }}
          package: ./angular-app

      - name: Deploy Django to Azure Web App (Backend)
        id: deploy-django
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'django-app-name'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_DJANGO }}
          package: ./django-app
